version: "3.9"

services:
  api:
    # Build from the Dockerfile in this folder
    build:
      context: .
      dockerfile: Dockerfile
    image: moderation-api:latest

    # Map container port -> host
    ports:
      - "8000:8000"

    # Mount code and data so you can edit locally and see changes live
    volumes:
      - ./backend:/app/backend:rw
      - ./cache/huggingface:/root/.cache/huggingface:rw

    # Fast dev reload
    command: >
      python -m uvicorn backend.app:app
      --host 0.0.0.0 --port 8000 --reload

    environment:
      # Speeds up model downloads and avoids Windows symlink warnings
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1

    # Restart policy
    restart: unless-stopped

    # OPTIONAL healthcheck: requires curl or wget in the image
    # (If you add curl in your Dockerfile, uncomment below)
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s
