name: CI

on:
  push:
    branches: [ main, improve/** ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fnmvp/fake-news-moderator-mvp/backend
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            fnmvp/fake-news-moderator-mvp/backend/requirements-ci.txt

      - name: Install dependencies (CI)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run tests
        run: |
          pytest -q

